version: '3.8'

networks:
  wired-net:
    external: true

services:
  attacker:
    build:
      context: ../containers/wired
      dockerfile: Containerfile
    image: localhost/wired:latest
    container_name: inici4rsesi0n_wired
    hostname: inici4rsesi0n_wired
    networks:
      wired-net:
        ipv4_address: ${ATTACKER_IP}
    volumes:
      - ../volumes/wired/scripts:/opt/scripts:rw
      - ../volumes/wired/evidence:/opt/evidence:rw
      - ../volumes/wired/reports:/opt/reports:rw
      - ${NVIM_CONFIG_PATH}:/root/.config/nvim:rw
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    environment:
      - LAB_PROFILE=recon
